# configs/lab/CausalExplorerEnv.toml
checkpoint_id = "jntphg79t04rck4o2bn75n3j" #resuming from last checkpoint saved from run gphiqync4t1uskiw49eh4g42
model = "allenai/OLMo-3-7B-Instruct"
max_steps = 500 #original run failed at step 346/500 so ~150 steps remaining
batch_size = 120
rollouts_per_example = 12
learning_rate = 3e-5

[buffer]
online_difficulty_filtering = true

[sampling]
max_tokens = 5000

[[env]]
id = "irfanjamil/CausalExplorerEnv@v0.2.2"
args = { num_examples = 250 }

[eval]
interval = 10                    # Evaluate every 10 steps

[[eval.env]]
id = "irfanjamil/CausalExplorerEnv"
num_examples = 50
rollouts_per_example = 3