# configs/lab/CausalExplorerEnv.toml
model = "allenai/OLMo-3-7B-Instruct"
max_steps = 300
batch_size = 120
rollouts_per_example = 12
learning_rate = 3e-5

[sampling]
max_tokens = 5000

[[env]]
id = "irfanjamil/CausalExplorerEnv@0.2.4"
args = { num_examples = 250 }

[eval]
interval = 10                    # Evaluate every 10 steps

[[eval.env]]
id = "irfanjamil/CausalExplorerEnv@0.2.4"
num_examples = 50
rollouts_per_example = 3